project_id = "dgmxndvvsbjjbnoibaid"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.guest-register]
verify_jwt = false

[functions.guest-signin]
verify_jwt = false

[functions.reset-guest-password]
verify_jwt = false

[functions.guest-messages]
verify_jwt = false

[functions.guest-folders]
verify_jwt = false

[functions.guest-folder-contents]
verify_jwt = false

[functions.reset-guest-password]
verify_jwt = false

[functions.guest-messages]
verify_jwt = false

[functions.guest-folders]
verify_jwt = false
